const test = require('brittle')
const path = require('bare-path')
const Helper = require('./helper')

const harness = path.join(Helper.root, 'test', 'fixtures', 'harness')
const minimal = path.join(Helper.root, 'test', 'fixtures', 'minimal')

class Rig {
  setup = async ({ comment }) => {
    this.helper = new Helper()
    comment('connecting local sidecar')
    await this.helper.ready()
    await this.helper.shutdown()
    this.helper = new Helper()
    await this.helper.ready()
    comment('local sidecar connected')
  }

  cleanup = async ({ comment }) => {
    comment('shutting down local sidecar')
    setTimeout(async () => {
      await this.helper.shutdown()
      comment('local sidecar shut down')
    }, 5000)
  }
}

const rig = new Rig()

test('commands setup', rig.setup)

test('pear stage --json <channel> <dir>', async function ({ plan, alike, is }) {
  plan(2)

  const testId = Math.floor(Math.random() * 100000)

  const argv = ['stage', '--json', 'test-' + testId, minimal]

  const running = await Helper.open(harness, { tags: ['exit'] }, { lineout: true })

  await running.inspector.evaluate(`
      __PEAR_TEST__.command(${JSON.stringify(argv)})
  `, { returnByValue: false })

  const seen = new Set()
  const tags = []
  for await (const line of running.lineout) {
    const result = JSON.parse(line)
    if (seen.has(result.tag)) continue
    seen.add(result.tag)
    tags.push(result.tag)
    if (result.tag === 'final') break
  }
  await running.inspector.evaluate('__PEAR_TEST__.ipc.close()', { returnByValue: false })
  await running.inspector.close()
  alike(tags, ['staging', 'byte-diff', 'summary', 'skipping', 'complete', 'addendum', 'final'])
  const { code } = await running.until.exit
  is(code, 0)
})

test.todo('pear init -y')
test.todo('pear init -y --force')
test.todo('pear init -y --type <type>')
test.todo('pear init -y --with <name>')
test.todo('pear init -y --type <type> --with <name> --force')

test.todo('pear stage <channel> <dir>')
test.todo('pear stage --dry-run <channel> <dir>')
test.todo('pear stage --dry-run --json <channel> <dir>')
test.todo('pear stage --bare <channel> <dir>')
test.todo('pear stage --bare --json <channel> <dir>')
test.todo('pear stage --ignore <list> <channel> <dir>')
test.todo('pear stage --ignore <list> --json <channel> <dir>')
test.todo('pear stage --truncate <n> <channel> <dir>')
test.todo('pear stage --truncate <n> --json <channel> <dir>')
test.todo('pear stage --name <name> <channel> <dir>')
test.todo('pear stage --name <name> --json <channel> <dir>')
test.todo('pear stage --ignore <list> --name <name> <channel> <dir>')
test.todo('pear stage --ignore <list> --name <name> --json <channel> <dir>')
test.todo('pear stage --dry-run --bare --ignore <list> --truncate <n> --name <name> <channel> <dir>')
test.todo('pear stage --dry-run --bare --ignore <list> --truncate <n> --name <name> --json <channel> <dir>')
test.todo('pear stage <link>')
test.todo('pear stage --json <link>')
test.todo('pear stage --dry-run <link>')
test.todo('pear stage --dry-run --json <link>')
test.todo('pear stage --bare <link>')
test.todo('pear stage --bare --json <link>')
test.todo('pear stage --ignore <list> <link>')
test.todo('pear stage --ignore <list> --json <link>')
test.todo('pear stage --truncate <n> <link>')
test.todo('pear stage --truncate <n> --json <link>')
test.todo('pear stage --name <name> <link>')
test.todo('pear stage --name <name> --json <link>')
test.todo('pear stage --ignore <list> --name <name> <link>')
test.todo('pear stage --ignore <list> --name <name> --json <link>')
test.todo('pear stage --dry-run --bare --ignore <list> --truncate <n> --name <name> <link>')
test.todo('pear stage --dry-run --bare --ignore <list> --truncate <n> --name <name> --json <link>')

test.todo('pear seed <channel> <dir>')
test.todo('pear seed --json <channel> <dir>')
test.todo('pear seed --seeders <key> <channel> <dir>')
test.todo('pear seed --seeders <key> --json <channel> <dir>')
test.todo('pear seed --name <name> <channel> <dir>')
test.todo('pear seed --name <name> --json <channel> <dir>')
test.todo('pear seed <link>')
test.todo('pear seed --json <link>')
test.todo('pear seed --seeders <key> <link>')
test.todo('pear seed --seeders <key> --json <link>')
test.todo('pear seed --name <name> <link>')
test.todo('pear seed --name <name> --json <link>')

test.todo('pear run <link>')
test.todo('pear run <link> --updates-diff')
test.todo('pear run <link> --no-updates')
test.todo('pear run <link> --entrypoint')
test.todo('pear run <link> --link <url>')
test.todo('pear run <link> --store <path>')
test.todo('pear run <link> --tmp-store')
test.todo('pear run <link> --unsafe-clear-app-storage')
test.todo('pear run <link> --unsafe-clear-preferences')
test.todo('pear run <link> --appling <path>')
test.todo('pear run <link> --checkout <n>')
test.todo('pear run <link> --checkout release')
test.todo('pear run <link> --checkout staged')
test.todo('pear run <link> --entrypoint <file> --store <path>')
test.todo('pear run <link> --entrypoint <file> --tmp-store')
test.todo('pear run <link> --entrypoint <file> --checkout <n> --unsafe-clear-app-storage --unsafe-clear-preferences')
test.todo('pear run <dir>')
test.todo('pear run <dir> --updates-diff')
test.todo('pear run <dir> --no-updates')
test.todo('pear run <dir> --entrypoint')
test.todo('pear run <dir> --link <url>')
test.todo('pear run <dir> --store <path>')
test.todo('pear run <dir> --tmp-store')
test.todo('pear run <dir> --unsafe-clear-app-storage')
test.todo('pear run <dir> --unsafe-clear-preferences')
test.todo('pear run <dir> --appling <path>')
test.todo('pear run <dir> --checkout <n>')
test.todo('pear run <dir> --checkout release')
test.todo('pear run <dir> --checkout staged')
test.todo('pear run <dir> --entrypoint <file> --store <path>')
test.todo('pear run <dir> --entrypoint <file> --tmp-store')
test.todo('pear run <dir> --entrypoint <file> --checkout <n> --unsafe-clear-app-storage --unsafe-clear-preferences')

test.todo('pear release <channel> <dir>')
test.todo('pear release --json <channel> <dir>')
test.todo('pear release --checkout <n> <channel> <dir>')
test.todo('pear release --checkout <n> --json <channel> <dir>')
test.todo('pear release --checkout staged <channel> <dir>')
test.todo('pear release --checkout staged --json <channel> <dir>')
test.todo('pear release --checkout release <channel> <dir>')
test.todo('pear release --checkout release --json <channel> <dir>')
test.todo('pear release <link>')
test.todo('pear release --json <link>')
test.todo('pear release --checkout <n> <link>')
test.todo('pear release --checkout <n> --json <link>')
test.todo('pear release --checkout staged <link>')
test.todo('pear release --checkout staged --json <link>')
test.todo('pear release --checkout release <link>')
test.todo('pear release --checkout release --json <link>')

test.todo('pear info')
test.todo('pear info --json <channel> <dir>')
test.todo('pear info <channel> <dir>')
test.todo('pear info --changelog <channel> <dir>')
test.todo('pear info --changelog --json <channel> <dir>')
test.todo('pear info --changelog --metadata <channel> <dir>')
test.todo('pear info --changelog --metadata --json <channel> <dir>')
test.todo('pear info --changelog --key <key> <channel> <dir>')
test.todo('pear info --changelog --key <key> --json <channel> <dir>')
test.todo('pear info --changelog --metadata --key <channel> <dir>')
test.todo('pear info --changelog --metadata --key --json <channel> <dir>')
test.todo('pear info --full-changelog <channel> <dir>')
test.todo('pear info --full-changelog --metadata <channel> <dir>')
test.todo('pear info --full-changelog --metadata --json <channel> <dir>')
test.todo('pear info --full-changelog --metadata --key <channel> <dir>')
test.todo('pear info --full-changelog --metadata --key --json <channel> <dir>')
test.todo('pear info --metadata <channel> <dir>')
test.todo('pear info --metadata --key <channel> <dir>')
test.todo('pear info --metadata --key --json <channel> <dir>')
test.todo('pear info --key <channel> <dir>')
test.todo('pear info --key --json <channel> <dir>')
test.todo('pear info --no-changelog <channel> <dir>')
test.todo('pear info --no-changelog --json <channel> <dir>')
test.todo('pear info --no-metadata <channel> <dir>')
test.todo('pear info --no-metadata --json <channel> <dir>')
test.todo('pear info --no-key <channel> <dir>')
test.todo('pear info --no-key --json <channel> <dir>')
test.todo('pear info --no-changelog --no-metadata <channel> <dir>')
test.todo('pear info --no-changelog --no-metadata --json <channel> <dir>')
test.todo('pear info --no-changelog --no-key <channel> <dir>')
test.todo('pear info --no-changelog --no-key --json <channel> <dir>')
test.todo('pear info --no-key --no-metadata <channel> <dir>')
test.todo('pear info --no-key --no-metadata --json <channel> <dir>')
test.todo('pear info --no-changelog --no-metadata --no-key <channel> <dir>')
test.todo('pear info --no-changelog --no-metadata --no-key --json <channel> <dir>')
test.todo('pear info <link>')
test.todo('pear info --json <link>')
test.todo('pear info --changelog <link>')
test.todo('pear info --changelog --json <link>')
test.todo('pear info --changelog --metadata <link>')
test.todo('pear info --changelog --metadata --json <link>')
test.todo('pear info --changelog --key <link>')
test.todo('pear info --changelog --key --json <link>')
test.todo('pear info --changelog --metadata --key <link>')
test.todo('pear info --changelog --metadata --key --json <link>')
test.todo('pear info --full-changelog <link>')
test.todo('pear info --full-changelog --metadata <link>')
test.todo('pear info --full-changelog --metadata --json <link>')
test.todo('pear info --full-changelog --metadata --key <link>')
test.todo('pear info --full-changelog --metadata --key --json <link>')
test.todo('pear info --metadata <link>')
test.todo('pear info --metadata --key <link>')
test.todo('pear info --metadata --key --json <link>')
test.todo('pear info --key <link>')
test.todo('pear info --key --json <link>')
test.todo('pear info --no-changelog <link>')
test.todo('pear info --no-changelog --json <link>')
test.todo('pear info --no-metadata <link>')
test.todo('pear info --no-metadata --json <link>')
test.todo('pear info --no-key <link>')
test.todo('pear info --no-key --json <link>')
test.todo('pear info --no-changelog --no-metadata <link>')
test.todo('pear info --no-changelog --no-metadata --json <link>')
test.todo('pear info --no-changelog --no-key <link>')
test.todo('pear info --no-changelog --no-key --json <link>')
test.todo('pear info --no-key --no-metadata <link>')
test.todo('pear info --no-key --no-metadata --json <link>')
test.todo('pear info --no-changelog --no-metadata --no-key <link>')
test.todo('pear info --no-changelog --no-metadata --no-key --json <link>')

test.todo('pear dump <link> <dir>')
test.todo('pear dump --checkout <n> <link> <dir>')
test.todo('pear dump --checkout staged <link> <dir>')
test.todo('pear dump --checkout release <link> <dir>')
test.todo('pear dump --json <link> <dir>')

test.todo('pear shift <source> <destination>')
test.todo('pear shift --json <source> <destination>')
test.todo('pear shift --force <source> <destination>')
test.todo('pear shift --force --json <source> <destination>')

test.todo('pear gc releases')
test.todo('pear gc releases --json')
test.todo('pear gc sidecars')
test.todo('pear gc sidecars --json')

test.todo('pear versions')
test.todo('pear versions --json')

// TODO: Unskip and implement the following after task "Paparam flag relationships"
test.skip('pear run <dir> --updates-diff --no-updates')
test.skip('pear run <dir> --store <path> --tmp-store')
test.skip('pear run <dir> --entrypoint <path> --appling <path>')
test.skip('pear info --full-changelog --changelog')

test('commands cleanup', rig.cleanup)
