// This runner is auto-generated by Brittle

await runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await test.load(import.meta.resolve('./inspect.test.js'))
  await test.load(import.meta.resolve('./touch.test.js'))
  await test.load(import.meta.resolve('./stage.test.js'))
  await test.load(import.meta.resolve('./seed.test.js'))
  await test.load(import.meta.resolve('./dump.test.js'))
  await test.load(import.meta.resolve('./provision.test.js'))
  await test.load(import.meta.resolve('./multisig.test.js'))
  await test.load(import.meta.resolve('./info.test.js'))
  await test.load(import.meta.resolve('./data.test.js'))
  await test.load(import.meta.resolve('./vanity.test.js'))
  await test.load(import.meta.resolve('./shutdown.test.js'))
  await test.load(import.meta.resolve('./changelog.test.js'))
  await test.load(import.meta.resolve('./cores.test.js'))
  await test.load(import.meta.resolve('./gc.test.js'))
  await test.load(import.meta.resolve('./blind-relay.test.js'))
  await test.load(import.meta.resolve('./blind-peer.test.js'))

  test.resume()
}
