// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./00-inspect.test.js')
  await import('./01-smoke.test.js')
  await import('./02-teardown.test.js')
  await import('./03-stage.test.js')
  await import('./04-seed.test.js')
  await import('./05-updates.test.js')
  await import('./06-run.test.js')
  await import('./07-dump.test.js')
  await import('./08-data.test.js')
  await import('./09-drop.test.js')
  await import('./10-shift.test.js')
  await import('./11-presets.test.js')
  await import('./12-touch.test.js')
  await import('./13-provision.test.js')
  await import('./14-info.test.js')
  await import('./15-shutdown.test.js')

  test.resume()
}
