// This runner is auto-generated by Brittle

runTests()

async function runTests() {
  const test = (await import('brittle')).default

  test.pause()

  await import('./00-inspect.test.js')
  await import('./01-touch.test.js')
  await import('./02-stage.test.js')
  await import('./03-seed.test.js')
  await import('./04-dump.test.js')
  await import('./05-provision.test.js')
  await import('./06-info.test.js')
  await import('./07-data.test.js')
  await import('./08-presets.test.js')
  await import('./09-shutdown.test.js')

  test.resume()
}
