// This file is autogenerated by the hyperdb compiler
/* eslint-disable camelcase */

const { IndexEncoder, c } = require('hyperdb/runtime')

const { version, resolveStruct } = require('./messages.js')

// '@pear/dht' collection key
const collection16_key = new IndexEncoder([
], { prefix: 16 })

function collection16_indexify (record) {
  return []
}

// '@pear/dht' reconstruction function
function collection16_reconstruct (version, keyBuf, valueBuf) {
  const value = c.decode(resolveStruct('@pear/dht/value', version), valueBuf)
  return value
}
// '@pear/dht' key reconstruction function
function collection16_reconstruct_key (keyBuf) {
  return {}
}

// '@pear/dht'
const collection16 = {
  name: '@pear/dht',
  id: 16,
  encodeKey (record) {
    const key = []
    return collection16_key.encode(key)
  },
  encodeKeyRange ({ gt, lt, gte, lte } = {}) {
    return collection16_key.encodeRange({
      gt: gt ? collection16_indexify(gt) : null,
      lt: lt ? collection16_indexify(lt) : null,
      gte: gte ? collection16_indexify(gte) : null,
      lte: lte ? collection16_indexify(lte) : null
    })
  },
  encodeValue (version, record) {
    return c.encode(resolveStruct('@pear/dht/value', version), record)
  },
  trigger: null,
  reconstruct: collection16_reconstruct,
  reconstructKey: collection16_reconstruct_key,
  indexes: []
}

module.exports = {
  version,
  collections: [
    collection16
  ],
  indexes: [
  ],
  resolveCollection,
  resolveIndex
}

function resolveCollection (name) {
  switch (name) {
    case '@pear/dht': return collection16
    default: return null
  }
}

function resolveIndex (name) {
  switch (name) {
    default: return null
  }
}
