// This file is autogenerated by the hyperschema compiler
// Schema Version: 1
/* eslint-disable camelcase */
/* eslint-disable quotes */

const VERSION = 1
const { c } = require('hyperschema/runtime')

// eslint-disable-next-line no-unused-vars
let version = VERSION

// @pear/node
const encoding0 = {
  preencode (state, m) {
    c.string.preencode(state, m.host)
    c.uint.preencode(state, m.port)
  },
  encode (state, m) {
    c.string.encode(state, m.host)
    c.uint.encode(state, m.port)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.uint.decode(state)

    return {
      host: r0,
      port: r1
    }
  }
}

// @pear/checkout
const encoding1 = {
  preencode (state, m) {
    c.uint.preencode(state, m.fork)
    c.uint.preencode(state, m.length)
  },
  encode (state, m) {
    c.uint.encode(state, m.fork)
    c.uint.encode(state, m.length)
  },
  decode (state) {
    const r0 = c.uint.decode(state)
    const r1 = c.uint.decode(state)

    return {
      fork: r0,
      length: r1
    }
  }
}

// @pear/asset.only
const encoding2_4 = c.array(c.string)

// @pear/asset
const encoding2 = {
  preencode (state, m) {
    c.string.preencode(state, m.link)
    c.string.preencode(state, m.path)
    c.string.preencode(state, m.ns)
    state.end++ // max flag is 2 so always one byte

    if (m.name) c.string.preencode(state, m.name)
    if (m.only) encoding2_4.preencode(state, m.only)
    c.uint.preencode(state, m.bytesAllocated)
  },
  encode (state, m) {
    const flags =
      (m.name ? 1 : 0) |
      (m.only ? 2 : 0)

    c.string.encode(state, m.link)
    c.string.encode(state, m.path)
    c.string.encode(state, m.ns)
    c.uint.encode(state, flags)

    if (m.name) c.string.encode(state, m.name)
    if (m.only) encoding2_4.encode(state, m.only)
    c.uint.encode(state, m.bytesAllocated)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const r2 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      link: r0,
      path: r1,
      ns: r2,
      name: (flags & 1) !== 0 ? c.string.decode(state) : null,
      only: (flags & 2) !== 0 ? encoding2_4.decode(state) : null,
      bytesAllocated: c.uint.decode(state)
    }
  }
}

// @pear/manifest
const encoding3 = {
  preencode (state, m) {
    c.uint.preencode(state, m.version)
  },
  encode (state, m) {
    c.uint.encode(state, m.version)
  },
  decode (state) {
    const r0 = c.uint.decode(state)

    return {
      version: r0
    }
  }
}

// @pear/dht.nodes
const encoding4_0 = c.array(c.frame(encoding0))

// @pear/dht
const encoding4 = {
  preencode (state, m) {
    state.end++ // max flag is 1 so always one byte

    if (m.nodes) encoding4_0.preencode(state, m.nodes)
  },
  encode (state, m) {
    const flags = m.nodes ? 1 : 0

    c.uint.encode(state, flags)

    if (m.nodes) encoding4_0.encode(state, m.nodes)
  },
  decode (state) {
    const flags = c.uint.decode(state)

    return {
      nodes: (flags & 1) !== 0 ? encoding4_0.decode(state) : null
    }
  }
}

// @pear/bundle.tags
const encoding5_3 = encoding2_4

// @pear/bundle
const encoding5 = {
  preencode (state, m) {
    c.string.preencode(state, m.link)
    c.string.preencode(state, m.appStorage)
    state.end++ // max flag is 2 so always one byte

    if (m.encryptionKey) c.fixed32.preencode(state, m.encryptionKey)
    if (m.tags) encoding5_3.preencode(state, m.tags)
  },
  encode (state, m) {
    const flags =
      (m.encryptionKey ? 1 : 0) |
      (m.tags ? 2 : 0)

    c.string.encode(state, m.link)
    c.string.encode(state, m.appStorage)
    c.uint.encode(state, flags)

    if (m.encryptionKey) c.fixed32.encode(state, m.encryptionKey)
    if (m.tags) encoding5_3.encode(state, m.tags)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const r1 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      link: r0,
      appStorage: r1,
      encryptionKey: (flags & 1) !== 0 ? c.fixed32.decode(state) : null,
      tags: (flags & 2) !== 0 ? encoding5_3.decode(state) : null
    }
  }
}

// @pear/gc
const encoding6 = {
  preencode (state, m) {
    c.string.preencode(state, m.path)
  },
  encode (state, m) {
    c.string.encode(state, m.path)
  },
  decode (state) {
    const r0 = c.string.decode(state)

    return {
      path: r0
    }
  }
}

// @pear/current.checkout
const encoding7_1 = c.frame(encoding1)
// @pear/current.assets
const encoding7_2 = c.array(c.frame(encoding2))

// @pear/current
const encoding7 = {
  preencode (state, m) {
    c.string.preencode(state, m.link)
    state.end++ // max flag is 2 so always one byte

    if (m.checkout) encoding7_1.preencode(state, m.checkout)
    if (m.assets) encoding7_2.preencode(state, m.assets)
  },
  encode (state, m) {
    const flags =
      (m.checkout ? 1 : 0) |
      (m.assets ? 2 : 0)

    c.string.encode(state, m.link)
    c.uint.encode(state, flags)

    if (m.checkout) encoding7_1.encode(state, m.checkout)
    if (m.assets) encoding7_2.encode(state, m.assets)
  },
  decode (state) {
    const r0 = c.string.decode(state)
    const flags = c.uint.decode(state)

    return {
      link: r0,
      checkout: (flags & 1) !== 0 ? encoding7_1.decode(state) : null,
      assets: (flags & 2) !== 0 ? encoding7_2.decode(state) : null
    }
  }
}

function setVersion (v) {
  version = v
}

function encode (name, value, v = VERSION) {
  version = v
  return c.encode(getEncoding(name), value)
}

function decode (name, buffer, v = VERSION) {
  version = v
  return c.decode(getEncoding(name), buffer)
}

function getEnum (name) {
  switch (name) {
    default: throw new Error('Enum not found ' + name)
  }
}

function getEncoding (name) {
  switch (name) {
    case '@pear/node': return encoding0
    case '@pear/checkout': return encoding1
    case '@pear/asset': return encoding2
    case '@pear/manifest': return encoding3
    case '@pear/dht': return encoding4
    case '@pear/bundle': return encoding5
    case '@pear/gc': return encoding6
    case '@pear/current': return encoding7
    default: throw new Error('Encoder not found ' + name)
  }
}

function getStruct (name, v = VERSION) {
  const enc = getEncoding(name)
  return {
    preencode (state, m) {
      version = v
      enc.preencode(state, m)
    },
    encode (state, m) {
      version = v
      enc.encode(state, m)
    },
    decode (state) {
      version = v
      return enc.decode(state)
    }
  }
}

const resolveStruct = getStruct // compat

module.exports = { resolveStruct, getStruct, getEnum, getEncoding, encode, decode, setVersion, version }
