name: Build Packages

on:
  workflow_dispatch:
    inputs:
      channel:
        type: choice
        default: dev
        options:
          - dev
          - stage
          - production
      upgrade-key:
        type: string
        description: Value for package.json upgrade field
        default: ''
        required: false
      run-linux-arm:
        type: boolean
        default: true
      run-macos:
        type: boolean
        default: true
      run-macos-intel:
        type: boolean
        default: false
      run-windows:
        type: boolean
        default: true
      run-stage:
        type: boolean
        default: false
      stage-dry-run:
        type: boolean
        default: true
      stage-namespace:
        type: string
        default: ''
      notify:
        type: boolean
        default: true

permissions:
  contents: write
  packages: read
  actions: write
  pull-requests: write

jobs:
  build:
    uses: holepunchto/pear-ci-build/.github/workflows/build.yml@main
    secrets: inherit
    with:
      ref: ${{ github.sha }}
      channel: ${{ inputs.channel }}
      upgrade-key: ${{ inputs.upgrade-key }}
      run-linux-arm: ${{ inputs.run-linux-arm }}
      run-macos: ${{ inputs.run-macos }}
      run-macos-intel: ${{ inputs.run-macos-intel }}
      run-windows: ${{ inputs.run-windows }}
      run-stage: ${{ inputs.run-stage }}
      stage-dry-run: ${{ inputs.stage-dry-run }}
      stage-namespace: ${{ inputs.stage-namespace }}
      notify: ${{ inputs.notify }}
