name: Bump Deps

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-deps:
    uses: holepunchto/actions/.github/workflows/bump-deps.yml@v1
    secrets: inherit
