name: Bump Versions

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Select version type to bump
        required: true
        options:
          - prerelease
          - patch
          - minor
          - major

jobs:
  bump-versions:
    # TODO: Use @main after merging https://github.com/holepunchto/actions/pull/1
    uses: holepunchto/actions/.github/workflows/bump-versions.yml@fe4796aadeb8d9357eee26df1fd934b4a6f09980 
    with:
      version: ${{ inputs.version }}
