name: Bump Version on Merged

on:
  pull_request:
    types: [closed]

env:
  version: ${{ github.event.pull_request.title }}
  channel-dev: ${{ contains(github.event.pull_request.labels.*.name, 'channel-dev') && 'true' }}
  channel-staging: ${{ contains(github.event.pull_request.labels.*.name, 'channel-staging') && 'true' }}
  channel-rc: ${{ contains(github.event.pull_request.labels.*.name, 'channel-rc') && 'true' }}

jobs:
  tag:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'bump-version') }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: holepunchto/actions/.github/steps/setup-repo@v1

      - name: Tag
        run: |
          echo ${{ env.version }}
          git tag ${{ env.version }}
          git push --tags

  build:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repo
        uses: holepunchto/actions/.github/steps/setup-repo@v1

      - name: Install keet-automation
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g @holepunchto/keet-automation

      - name: Build
        run: |
          channel=dev
          if [[ ${{ env.channel-staging }} == 'true' ]]; then
            channel=stage
          elif [[ ${{ env.channel-rc }} == 'true' ]]; then
            channel=rc
          fi
          echo "Building for $channel"

          keet-automation \
            --seed ${{ secrets.AUTOMATION }} \
            --remote c855820b0f7586b90a033b655aa97e713266fee588754223a29c489f540ef68d pear-platform \
            --commit ${{ github.sha }} \
            --channel $channel
            --notify true
