name: Bump Deps

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Select version type to bump
        required: true
        options:
          - prerelease
          - patch
          - minor
          - major

jobs:
  bump-deps:
    # TODO: Use @main after merging https://github.com/holepunchto/actions/pull/1
    uses: holepunchto/actions/.github/workflows/bump-versions.yml@87f1c8e3ef71f8659b08a4dbed0e28b3068aad3f 
    with:
      version: ${{ inputs.version }}
