name: Bump Deps

on:
  workflow_dispatch:

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Deps
        id: bump-deps
        # TODO: Use @main after merging https://github.com/holepunchto/actions/pull/1
        uses: holepunchto/actions/.github/steps/bump-deps@87f1c8e3ef71f8659b08a4dbed0e28b3068aad3f
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
