name: Bump Deps

on:
  workflow_dispatch:

jobs:
  bump-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Git config
        run: |
          git config user.name 'GitHub Actions Bot'
          git config user.email 'bot@github.actions.com'

      - name: Bump Deps
        uses: holepunchto/actions/.github/steps/bump-deps@v1
        with:
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
