name: Bump Deps

on:
  workflow_dispatch:

jobs:
  bump-deps:
    # TODO: Use @main after merging https://github.com/holepunchto/actions/pull/1
    uses: holepunchto/actions/.github/workflows/bump-deps-v2.yml@fe4796aadeb8d9357eee26df1fd934b4a6f09980
