name: Bump Versions

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Select version type to bump
        required: true
        options:
          - prerelease
          - patch
          - minor
          - major

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Bump Versions
        id: bump-versions
        # TODO: Use @main after merging https://github.com/holepunchto/actions/pull/1
        uses: holepunchto/actions/.github/steps/bump-versions@0f453ede95e75ef1857b42b359bf57da62f36d30
        with:
          use-checkout: true
          use-git-config: true
          use-create-pr: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
