name: Bump Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Select version type to bump
        required: true
        options:
          - prerelease
          - patch
          - minor
          - major
      channel:
        type: choice
        description: Select channel to build
        required: true
        options:
          - dev
          - stage
          - rc

jobs:
  bump-version:
    uses: holepunchto/actions/.github/workflows/bump-version.yml@v1
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      labels: 'bump-version,channel-${{ inputs.channel }}'
  
  notify-slack:
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        uses: holepunchto/actions/.github/steps/notify-slack@v1
        with:
          auth_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: "#pear-platform"
          message: "Please review: Bump Version ${{ needs.bump-version.outputs.pull-request-url }}"
