name: Build Status
on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: holepunchto/actions/bare-base@v1

      - name: Install fixture dependencies
        shell: bash
        run: for dir in test/fixtures/*/; do (cd "$dir" && npm install --install-links); done

      - name: Install w/ dev deps
        run: npm install

      - name: Test
        run: npm test
