name: Ignored

on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Select version type to bump
        required: true
        options:
          - prerelease
          - patch
          - minor
          - major

jobs:
  bump-deps:
    uses: holepunchto/actions/.github/workflows/bump-deps-v2.yml@0f453ede95e75ef1857b42b359bf57da62f36d30
  
  bump-versions:
    uses: holepunchto/actions/.github/workflows/bump-versions.yml@0f453ede95e75ef1857b42b359bf57da62f36d30 
    with:
      version: ${{ inputs.version }}
  