name: Build Status
on:
  schedule:
    - cron: '0 10 * * *'
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  repository_dispatch:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint

  build:
    name: ${{ matrix.host }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            host: linux-x64
          - os: ubuntu-24.04-arm
            host: linux-arm64
          - os: macos-latest
            host: darwin-arm64
          - os: windows-latest
            host: win32-x64
          - os: windows-11-arm
            host: win32-arm64
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - name: Setup repo
        uses: holepunchto/actions/.github/steps/setup-repo@v1

      - name: Install w/ dev deps
        run: npm ci

      - name: Build Local Runtime
        run: npm run make

      - name: Run Pear on Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          Write-Host "=== make contains ==="
          Get-ChildItem .\out\make

          Write-Host "=== running pear ==="
          .\out\make\pear.exe

          Write-Host "=== running pear -v ==="
          .\out\make\pear.exe -v

          Write-Host "=== running pear help ==="
          .\out\make\pear.exe help
        shell: pwsh

      - name: Run Pear on Linux/macOS
        if: ${{ runner.os != 'Windows' }}
        run: |
          echo "=== make contains ==="
          ls ./out/make

          echo "=== running pear ==="
          ./out/make/pear

          echo "=== running pear -v ==="
          ./out/make/pear -v

          echo "=== running pear help ==="
          ./out/make/pear help
        shell: pwsh

      - name: Install Bare
        run: npm i -g bare-runtime

      - name: Test
        run: npm test
