name: Integrate

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'

permissions:
  contents: read
  checks: write

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: holepunchto/actions/node-base@v1
      - run: npm run lint

  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    runs-on: ${{ matrix.os }}
    name: Test / ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: holepunchto/actions/bare-base@v1
      - run: npm install
      - run: npm run bootstrap
      - run: npm test
